name: cyclesync
description: A Flutter app for cycle tracking.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Routing package
  go_router: ^16.0.0

  # Firebase Core
  firebase_core: ^3.13.1

  # Firebase Authentication
  firebase_auth: ^5.5.4

  # Cloud Firestore (for period tracking data)
  cloud_firestore: ^5.6.8

  # State management
  provider: ^6.1.2

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
