// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwuPYtFM9W3JMPRpC-QzyCCE57BAH_HAw',
    appId: '1:730237632589:web:ad0b281989285ce2fb9c04',
    messagingSenderId: '730237632589',
    projectId: 'cyclesync-app',
    authDomain: 'cyclesync-app.firebaseapp.com',
    storageBucket: 'cyclesync-app.firebasestorage.app',
    measurementId: 'G-X11MH79GPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYq1-JZXaHTUaSwWSjioqnSqsNTZX5UDY',
    appId: '1:730237632589:android:d7d214c876da6a51fb9c04',
    messagingSenderId: '730237632589',
    projectId: 'cyclesync-app',
    storageBucket: 'cyclesync-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJws11x_k1jyjeEBbb6lOz1WsVQO-EP3s',
    appId: '1:730237632589:ios:ef54993e2578decffb9c04',
    messagingSenderId: '730237632589',
    projectId: 'cyclesync-app',
    storageBucket: 'cyclesync-app.firebasestorage.app',
    iosClientId: '730237632589-mp9ncc6781pmjk64i513q9pec7cc29da.apps.googleusercontent.com',
    iosBundleId: 'com.example.cyclesync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJws11x_k1jyjeEBbb6lOz1WsVQO-EP3s',
    appId: '1:730237632589:ios:ef54993e2578decffb9c04',
    messagingSenderId: '730237632589',
    projectId: 'cyclesync-app',
    storageBucket: 'cyclesync-app.firebasestorage.app',
    iosClientId: '730237632589-mp9ncc6781pmjk64i513q9pec7cc29da.apps.googleusercontent.com',
    iosBundleId: 'com.example.cyclesync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwuPYtFM9W3JMPRpC-QzyCCE57BAH_HAw',
    appId: '1:730237632589:web:ad0b281989285ce2fb9c04',
    messagingSenderId: '730237632589',
    projectId: 'cyclesync-app',
    authDomain: 'cyclesync-app.firebaseapp.com',
    storageBucket: 'cyclesync-app.firebasestorage.app',
    measurementId: 'G-X11MH79GPC',
  );

}